name:                moduleCalc
version:             0.1.0.0
github:              "strudjay/moduleCalc"
license:             BSD3
author:              "Jaden Strudwick"
maintainer:          "strudjay@gmail.com"
copyright:           "2022 Jaden Strudwick"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JadenStrudwick/moduleCalc#readme>

dependencies:
- base >= 4.7 && < 5
- threepenny-gui

library:
  source-dirs: src

executables:
  moduleCalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moduleCalc

tests:
  moduleCalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moduleCalc
